server:
  port: 8888

mybatis:
  type-aliases-package: com.yxchen.hotspot.commom.bean

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.224.8.158:3306/db_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull\&useCursorFetch=true&defaultFetchSize=1000&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456